apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-vm-pvc-0
  namespace: dev-w6vw5
  labels:
    vm-selector: mysql-vm
  annotations:
    csi.vsphere.volume-requested-topology: '[{"topology.kubernetes.io/zone":"zone1"}]'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: vi1-paris-cl01-vsan