apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3ta-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/3ta-demo'
    targetRevision: main
    path: 3ta/apps/3ta-app
    directory:
      recurse: true
  destination:
    # This is critical: you want to deploy to the newly registered cluster
    # Use the cluster context name that Argo CD sees after registration
    name: 'supervisor:vks-01:vks-01'
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Deploy after the cluster is registered
  syncWave: 2
