apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-service-account
---
apiVersion: v1
kind: Secret
metadata:
  name: test-service-account-token
  annotations:
    kubernetes.io/service-account.name: test-service-account
type: kubernetes.io/service-account-token
data:
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklsaGhNVGxvTmtoU1RuRktNRE5uVlRjeVNYSm9XREYxV0VkdmIwOVZjM1kzV1hjNWVrWldlWFptVEdNaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWlhZdGR6WjJkelVpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pYVc1MFpYSnVZV3d0WVhCd0xYUnZhMlZ1SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1SbGRuUnZiMnh6SWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pWkdSa01qSXhaVEl0T0dObVpTMDBPVEJtTFdFNVltSXRPV0kwT0RVM01EVTJZbUV4SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tUmxkaTEzTm5aM05UcGtaWFowYjI5c2N5SjkuOEhxLTFTakRHWktCM2t6S2FvUzlHazRWLW9IV0dlT2VnOERHZkRHNGVDTnQ1d1JUZUl2b0FpbENQbGdDbVZRMWNVekFFZkpUYXdTSkVCbk9tSjhjVkFxcnlmVi1VUDBta0VLZ0tGTm40N2dVak1IZXlRdnAtNmg3N1lTbGFEclpYSi1Bc2w1RUxtOFRzWnY2WWlzWnRJY1JNa1FRNmxIdTFKSW5lT01TMVdScm1uSTdSeXNQMERPeFlJZ1hKQWpmeDVfMFh1anp3UGdPanJXVDY5ZU4tOFhGN1M1Zk5PN3BfbldmQWlrOVJkMmxDczF3RlYyUUVpYkFNVHhxck5lQVYtSkNzM1J1ZTZHbHRZRndEMFF1QWpZSmN3eTk4ZzRsb3dEcG0ydGlmWFRBYS1Gc0d4MzZzNTVDRFdkWHhXV0tMSjF6T051N2ZYaTc1WUxRTHRPel9n
