apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3ta-parent
  namespace: dev-w6vw5
spec:
  project: default
  source:
    repoURL: 'https://github.com/KBrookfield/3ta-demo'
    targetRevision: main
    path: 3ta/child-apps    
    directory:
      recurse: true   
  destination:
    server: 'https://32.32.0.2:443'
    namespace: dev-w6vw5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true